Level 2
DmitrySerzhantov/movies-explorer-frontend pull request #1
Opened 2023-07-26 04:30 UTC by DmitrySerzhantov

2023-07-26 05:50 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* Проект тянется на больших экранах, хорошо бы зафиксировать макс. ширину по макету с центрированием по вьюпорту
* https://yadi.sk/i/46vxyRn6nXMu7Q карточки с сохраненными видео отличаются логикой по макету и не соотв. в проекте.
* https://yadi.sk/d/XAv_KEylNw5T2Q прозрачность только у границы, текст не имеет прозрачности по макету
* https://yadi.sk/d/x7TiOEFseCuYMA - нет мобильного меню

* https://yadi.sk/d/9xpT_hn53sAWEw https://yadi.sk/d/wvsVugzwSWSEBA https://yadi.sk/d/naOsbB2OiD9HBA всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).

Главная
* 768 https://yadi.sk/d/QhDg3A-D8Z8OhQ / 320 https://yadi.sk/d/4xaHhVrlbmF4_Q
* 768 / 320 https://yadi.sk/d/p4fRi_HZpC_9-w цвет границы немного отличается

Регистрация
* все разрешения https://yadi.sk/d/0LsxJfaLnlf1Uw

404
* 320 https://yadi.sk/d/c_nOlxfzt_6eGw

Фильмы
* 1280 https://yadi.sk/d/Mq0q6oaAG2e-5w
* 768 https://yadi.sk/d/x7TiOEFseCuYMA
* 320 https://yadi.sk/d/EYB99Y5D6Wqq6w

Сохраненные
* Все разрещения https://yadi.sk/d/zCzbabiVy1z_VQ в макете есть отступ до подвала и нет кнопки еще

Профиль
* 1280 https://yadi.sk/d/ZbrfzQS1E5ijWA
* 768 https://yadi.sk/d/dMJREWdnfHHFFw
* 320 https://yadi.sk/d/HY2t7uCsu9u55g

Меню
* 768 https://yadi.sk/d/TuaImJVdMzSV7w
* 320 https://yadi.sk/d/GiQcAKc3mmam9A

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/hk04AtlEClfbqg горизонтальная прокрутка. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

* https://github.com/DmitrySerzhantov/how-to-learn - ошибка 404

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/Vi9udKZUv46-LQ небольшие ошибки
* https://yadi.sk/i/9HRnr74inw9nAg здесь лучше подойдут сложные модификаторы по типу `ключ_значение`, скорректируйте везде по аналогии

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/O236DvlGqfcVww между карточками большие отступы, можно центрировать макет или сделать ширину карточек отзывчивой
* https://yadi.sk/i/s93d5aXJJWv4Tw https://yadi.sk/d/0QcuB3eFlfKOzw В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

* https://yadi.sk/d/V-B02G48YBvxfQ объедините ссылку с иконкой, чтобы не было дублей. Хорошей практикой считается отображать декоративные изображения на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
* https://yadi.sk/d/PfoRRnNNMQig7g вытяните подвал из main
* https://yadi.sk/d/7BSQhuGNx2beHw используйте nav для навигационных списков
* https://yadi.sk/d/fxlegl3Mt1ChWw для хедера используйте сем. тег header
* https://yadi.sk/d/827STSmVCjlnxQ главные блоки проекта оформите main, footer header вытяните

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* https://yadi.sk/d/x7xLXRcvBXmoUA нет ховер эффекта
* https://yadi.sk/d/XNG5n3yXGvtDDg нет смены состояния активного флажка как в макете

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [ ] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.

* https://yadi.sk/d/HCWE0kAewe8RKg https://yadi.sk/d/AG7OYV66vXa8PQ Всем полям следует стилизовать состояния focus и outline по макету или на свое усмотрение, чтобы при переключении через tab или установлении фокуса, было визуально выделено поле.

- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* https://yadi.sk/d/AG7OYV66vXa8PQ Всем полям следует установить placeholder со значениями, напр., `placeholder="Ваше имя..."`
- Поля не проходят обязательную валидацию, должен быть required, type и отображение ошибки при неверно заполненном поле/пустом

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [ ] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.

* https://yadi.sk/d/rQu1sKWwUabLDA не указаны альт.шрифты

- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 42

## Доп. Комментарии:
- Мобильное меню и меню в десктопной версии можно оформить одним элементом, смену вида можно стилизовать через брейкпоинты.

2023-07-30 07:08 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 2 ревью Вашего проекта, остались моменты, которые можно еще доработать просмотрите комментарии в чеклисте.
Проект не запустился, в доп.ком. указала, что нужно скорректировать.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/d/YHF6wondkqx4pg - нет мобильного меню, бургер следует добавить на брейкпоинтах от 768 и меньше. Вам нужно поработать с брейкпоинтами для корректного отображения.

* https://yadi.sk/d/BX5zQQuCZ2Wsqw, следует немного скорректировать, вместо vh используйте авто отступы и укажите минимальную высоту блоку. Сейчас кнопка и лого имеют фиксированные отступы и растягиваются на вьюпорте не по макету https://yadi.sk/d/WP-quDAw-bzinw. https://yadi.sk/d/hVK6TChMusx__g вот примерно так на страницах 404 регистрация/вход. В профиле также, только там шапка сверху прибита https://yadi.sk/d/WzWakJhJsT9nog.

Регистрация
* все разрешения https://yadi.sk/d/3gynyAAToTCTug https://yadi.sk/d/w8d7EPjjxRVrjQ https://yadi.sk/d/Z-K890uzLktn6w

Фильмы
* 320 https://yadi.sk/d/3Gmd-E1HjB9fCA

Сохраненные
* Все разрещения https://yadi.sk/d/s6I1ll0JKrpRrQ https://yadi.sk/d/SgiVUqnVIhZvhg https://yadi.sk/d/fXBXerv2JpNqjw
* https://yadi.sk/d/Nc3ddaLuaMMchA

Профиль
* 1280 https://yadi.sk/d/H4WGGXBYqOyEyQ
* 768 https://yadi.sk/d/mvp_U3G8ZfmAMQ
* 320 https://yadi.sk/d/gWHE1aYyzqUK8w

Меню
* 768 https://yadi.sk/d/1O4u2n1-9vRWMQ
* 320 https://yadi.sk/d/3IOMhAtC0QD0hg

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/r2-TsImVznDklQ https://yadi.sk/d/rJvVtUsrtZKDew https://yadi.sk/d/9obto5kVX4ITAg сохраняется горизонтальная прокрутка. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

- https://yadi.sk/d/niCMEz3SGgJhmQ при нажатии на кнопки необходимо проверять заполненность полей, если поля заполнены некорректно/пустые, указывать ошибки.

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 75

## Доп. Комментарии:
- https://yadi.sk/d/OKdREYl1UsvBtA ошибки при запуске проекта, скорректируйте именование файла

2023-07-31 05:49 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 3 ревью Вашего проекта, немного нехватило, есть еще гор.прокрутка, указала блоки, в которых она образуется на главной странице при сужении.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

Сохраненные
* 1280 https://yadi.sk/d/U-UfR71_f_ObbA

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/mL3rUVfbhwVFow в главной секции, https://yadi.sk/d/33f3FW3syy12tg в технологиях еще сохраняется скролл

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 77

2023-07-31 18:48 UTC, DmitrySerzhantov commented
> # Резюме по работе:
> Здравствуйте! Готово 3 ревью Вашего проекта, немного нехватило, есть еще гор.прокрутка, указала блоки, в которых она образуется на главной странице при сужении.
> 
> ## Верстка и JSX
> ### Критерии, влияющие на работоспособность
> * [ ]   Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
> 
> Сохраненные
> 
> * 1280 https://yadi.sk/d/U-UfR71_f_ObbA
> 
> * [ ]   Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
> 
> * https://yadi.sk/d/mL3rUVfbhwVFow в главной секции, https://yadi.sk/d/33f3FW3syy12tg в технологиях еще сохраняется скролл
> 
> * [x]   Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
> * [x]   Именование классов сделаны по БЭМ.
> * [x]   Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
> * [x]   В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
> * [x]   Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
> * [x]   Каркас макета реализован на Flex layout или Grid layout;
> * [x]   Инфраструктурные файлы проекта созданы через CRA.
> * [x]   Работа модальных окон настроена.
> * [ ]  Разметка портирована в JSX:
>   
>   * [x]   разметка заключена в ( ), лишние пустые  для этого не используются;
>   * [x]   разметка вынесена в соответствующие ей компоненты.
> * [ ]  В проекте есть:
>   
>   * [x]   директория images/ с картинками,
>   * [x]   директория components/ с JS и CSS-файлами компонентов,
>   * [x]   директория fonts/ со шрифтами.
> 
> ### Хорошие практики
> * [x]   Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
> * [x]   В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
> * [x]   Шрифты подключены через @font-face.
> * [x]   Иконки экспортированы в формате SVG.
> * [x]   Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
> * [x]   У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
> * [x]   reset.css запрещен.
> 
> ### Рекомендации
> * [x]   Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
> * [x]   Для изображений задан атрибут alt с подходящий значением.
> * [x]   Растровые и векторные изображения оптимизированы;
> 
> ## Количество баллов: 77
![2023-07-31_21-06-19](https://github.com/DmitrySerzhantov/movies-explorer-frontend/assets/116765010/c68392c1-2ecf-40c5-8bb3-07741ea3569a)

![2023-07-31_21-15-44](https://github.com/DmitrySerzhantov/movies-explorer-frontend/assets/116765010/8097b969-3b5b-4fb8-a632-1d4c043d6e2e)
Подскажите пожалуйста как верно это исправить не совсем понимаю что не так. ведь футер прижат к низу страницы и с увеличение двигается  вниз.  попробовал выставить точные размеры как в макете все совпадает. со скролом по горизонтали  вроде разобрался. но он у меня тоже не отображался. какую версию браузера можно использовать.

2023-08-01 15:12 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Поздравляю, Ваш проект принят! Желаю Вам успехов во всех начинаниях! 
Сразу хочу попросить прощения, в прошлый раз не засчитала балл за первый пункт, ошибочно выставленная высота сбила меня с толку.
В данной проверке был исправлен также гор.скролл, что дало Вам в общей сумме 100 баллов по чек листу. С чем Вам сердечно поздравляю!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 100

2023-08-03 17:42 UTC, merged